export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const SORT_PRODUCTS = 'SORT_PRODUCTS';
